<?php

namespace App\Http\Controllers;

use App\Models\Session;
use Illuminate\Http\Request;
use FFMpeg\FFMpeg;
use FFMpeg\Format\Video\X264;
use Intervention\Image\ImageManager;
use Intervention\Image\Drivers\Gd\Driver;

class CameraController extends Controller
{
    /**
     * Process Unified Session: Receives 1 video and 3 photos
     * Generates a Photo Strip and a GIF from them using the selected template.
     */
    public function processSession(Request $request)
    {
        try {
            $request->validate([
                'session_id' => 'required|exists:sessions,id',
                'video' => 'required|file',
                'photos' => 'required|array|min:1',
                'photos.*' => 'required|file',
                'template' => 'nullable|string'
            ]);

            \Log::info("Process Session started", ['session_id' => $request->session_id]);

            $sessionId = $request->session_id;
            $session = Session::find($sessionId);
            
            $outputDir = storage_path('app/public/output');
            if (!file_exists($outputDir)) {
                mkdir($outputDir, 0777, true);
            }

            // 1. Save Video
            $videoFile = $request->file('video');
            $videoName = "bts_{$sessionId}." . $videoFile->getClientOriginalExtension();
            $videoFile->move($outputDir, $videoName);
            $videoPath = "{$outputDir}/{$videoName}";
            $videoUrl = url("/storage/output/{$videoName}");

            // 2. Save Photos & Generate Photo Strip
            $photos = $request->file('photos');
            $imagePaths = [];
            
            // Save individual photos
            foreach ($photos as $index => $photo) {
                $photoName = "frame_{$sessionId}_{$index}.jpg";
                $photo->move($outputDir, $photoName);
                $imagePaths[] = "{$outputDir}/{$photoName}";
            }

            // Merge using Intervention Image v4
            $manager = new ImageManager(new Driver());
            
            // Standard Photobooth Strip Size (2x6 inches at 300 DPI = 600 x 1800 pixels)
            $stripWidth = 600;
            $stripHeight = 1800;

            // --- STEP 1: Place template as the BASE BACKGROUND ---
            $templateName = $request->input('template', null);
            $templatePath = $templateName ? public_path("images/{$templateName}") : null;

            // If no valid template is given, start with a white canvas
            if ($templatePath && file_exists($templatePath)) {
                $canvas = $manager->decodePath($templatePath);
                if ($canvas->width() !== $stripWidth || $canvas->height() !== $stripHeight) {
                    $canvas->scale(width: $stripWidth, height: $stripHeight);
                }
            } else {
                $canvas = $manager->createImage($stripWidth, $stripHeight)->fill('ffffff');
            }
            
            // --- STEP 2: Paste photos ON TOP of the template using auto-detected slot positions ---
            // Slot data generated by detect_slots.php based on white areas in each template.
            $templateConfigs = [
                // 4 landscape slots: w=530, h=304
                'frame_1.png' => [
                    'slots' => [
                        ['x' => 34,  'y' => 112,  'w' => 530, 'h' => 304],
                        ['x' => 34,  'y' => 456,  'w' => 529, 'h' => 304],
                        ['x' => 35,  'y' => 799,  'w' => 528, 'h' => 305],
                        ['x' => 34,  'y' => 1143, 'w' => 530, 'h' => 304],
                    ],
                ],
                // 3 slots of various sizes - only use the 3 real photo boxes
                'frame_2.png' => [
                    'slots' => [
                        ['x' => 89,  'y' => 466,  'w' => 421, 'h' => 335],
                        ['x' => 89,  'y' => 800,  'w' => 421, 'h' => 335],
                        ['x' => 89,  'y' => 1135, 'w' => 421, 'h' => 335],
                    ],
                ],
                // 3 landscape slots
                'frame_3.png' => [
                    'slots' => [
                        ['x' => 60,  'y' => 134,  'w' => 489, 'h' => 259],
                        ['x' => 60,  'y' => 527,  'w' => 489, 'h' => 362],
                        ['x' => 60,  'y' => 920,  'w' => 489, 'h' => 260],
                    ],
                ],
                // 4 landscape slots (generated template)
                'frame_sample.png' => [
                    'slots' => [
                        ['x' => 50,  'y' => 100,  'w' => 500, 'h' => 281],
                        ['x' => 50,  'y' => 431,  'w' => 500, 'h' => 281],
                        ['x' => 50,  'y' => 762,  'w' => 500, 'h' => 281],
                        ['x' => 50,  'y' => 1093, 'w' => 500, 'h' => 281],
                    ],
                ],
            ];

            $config = $templateConfigs[$templateName] ?? $templateConfigs['frame_1.png'];

            foreach ($imagePaths as $index => $imgPath) {
                $slot = $config['slots'][$index] ?? null;
                if (!$slot) break;
                // Crop and resize photo to exactly fill the detected slot rectangle
                $img = $manager->decodePath($imgPath)->cover(width: $slot['w'], height: $slot['h']);
                $canvas->insert($img, $slot['x'], $slot['y'], 'top-left');
            }

            $stripName = "strip_{$sessionId}.jpg";
            $stripPath = "{$outputDir}/{$stripName}";
            $canvas->save($stripPath);
            $stripUrl = url("/storage/output/{$stripName}");

            // 3. Generate GIF using Intervention Image
            $gifName = "gif_{$sessionId}.gif";
            $gifPath = "{$outputDir}/{$gifName}";
            
            // Create animation from the uploaded photos (like a classic boomerang/photobooth GIF)
            // Scale them down to something smaller like 400px width for the GIF to save size
            $firstImg = $manager->decodePath($imagePaths[0]);
            $gifWidth = 400;
            $gifRatio = $gifWidth / $firstImg->width();
            $gifHeight = (int) ($firstImg->height() * $gifRatio);

            $gifImage = $manager->createImage($gifWidth, $gifHeight, function ($animation) use ($imagePaths) {
                foreach ($imagePaths as $path) {
                    // Add each photo as a frame with 0.5 seconds delay
                    $animation->add($path, 0.5);
                }
            });
            $gifImage->setLoops(0)->save($gifPath);
            $gifUrl = url("/storage/output/{$gifName}");

            // 4. Update Session Data
            $session->update([
                'status' => 'completed',
                // We use final_file to store a JSON array of all 3 URLs for simplicity, 
                // or just the strip as primary and others in QR code
                'final_file' => json_encode([
                    'strip' => $stripUrl,
                    'gif' => $gifUrl,
                    'video' => $videoUrl
                ]),
                'qr_code' => $stripUrl // Simplification: we could link to a download page
            ]);

            return response()->json([
                'success' => true,
                'message' => 'Session processed successfully',
                'session_id' => $sessionId,
                'urls' => [
                    'strip' => $stripUrl,
                    'gif' => $gifUrl,
                    'video' => $videoUrl
                ]
            ]);
        } catch (\Illuminate\Validation\ValidationException $e) {
            \Log::error("Validation Error in Process Session: " . json_encode($e->errors()));
            return response()->json(['success' => false, 'message' => 'Validation failed: ' . json_encode($e->errors())], 422);
        } catch (\Exception $e) {
            \Log::error("Error in Process Session: " . $e->getMessage() . "\n" . $e->getTraceAsString());
            return response()->json(['success' => false, 'message' => 'Server error: ' . $e->getMessage()], 500);
        }
    }
}
